name: gendiff-check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry add --group dev flake8
          poetry add --group dev pytest
          poetry add --group dev pytest-cov
          poetry add PyYAML
          make install
          make build
      - name: Run linter
        run: make lint
      - name: Run pytest
        run: make pytest
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 479179111cb85531ff3b388ac8f4bf3ee47edc9a3d390a80775c9a25663b933e
        with:
          coverageCommand: make test-coverage
          debug: true